---
- name deploy vsftpd
  hosts: ftpserver

  tasks:
  - name: install vsftpd
    ansible.builtin.apt:
        name:
          - vsftpd
          - ssl-cert
        update_cache: true
  - name: Start vsftpd
      ansible.builtin.service:
        name: vsftpd
        state: started
        enabled: true
  - name: create readme file
    copy:
      content: "free downloads for everybody"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444