---
- name: Install core packages
  hosts: group1,group2
  become: true

  tasks:
    - name: Install core packages
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - nfs-common
        update_cache: true