---
- name: Install qemu-guest-agent package
  hosts: agroup1,group2
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present