---
- name: Install zsh
  hosts: group1,group2
  become: true

  tasks:
    - name: Install zsh
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: true
      become: true