---
- name deploy vsftpd
  hosts: ftpserver

  tasks:
  - name: install vsftpd
    apt: name=vsftpd
  - name: enable vsftpd
    service: name=vsftpd enabled=true
  - name: create readme file
    copy:
      content: "free downloads for everybody"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444